### ISSUE TITLE
MatchMaking - Shuffle bug

### ISSUE THREAD

**Issue by JoeBSong** [tvledesign/standard-deck-manager#20]
When reaching the last 4 cards and hitting Play again, 2 cards will be dealt out but freezes and gets a ArgumentOutOfRangeException Error.

![image](https://user-images.githubusercontent.com/31709530/52245360-f44ed500-28a6-11e9-8c3d-1ca8f916d3a9.png)

**Comment by JoeBSong** [comment]
Confirmed fixed.

**Comment by ChristopherYarka** [comment]
Can also confirm it has been fixed. @tvledesign
