### ISSUE TITLE
BlackJack - Card counting

### ISSUE THREAD

**Issue by JoeBSong** [tvledesign/standard-deck-manager#21]
When playing the game BlackJack, there are times where pressing hit the next card does not add. sometimes pressing hit the point goes down, and sometimes suddenly the points a different number.

Card did not add the Jack.
![image](https://user-images.githubusercontent.com/31709530/52377885-c8a92780-2a2b-11e9-8cd2-95f454f0ab8b.png)

Card Counter suddenly changing. It was 21 before I hit again then changed to 12
![image](https://user-images.githubusercontent.com/31709530/52378026-31909f80-2a2c-11e9-9939-9773d05839ca.png)

This is after the sudden change able to add more cards in hand. Clearly way over 21.
![image](https://user-images.githubusercontent.com/31709530/52378157-8fbd8280-2a2c-11e9-92d6-f38b4ea2c272.png)

**Comment by tvledesign** [comment]
Not a bug. If the cards add up to over 21 ace gets read as a one.
