### ISSUE TITLE
2018.1.9f2 - Adding card

### ISSUE THREAD

**Issue by JoeBSong** [tvledesign/standard-deck-manager#22]
Able to add a card but upon saving, switch, and back some of the cards change

Before
![image](https://user-images.githubusercontent.com/31709530/54468271-e4090000-4758-11e9-8825-fa53902413c7.png)

After
![image](https://user-images.githubusercontent.com/31709530/54468276-eec39500-4758-11e9-926e-e8c28887f5bf.png)

**Comment by JoeBSong** [comment]
Upon testing again, it seems to be only the last card added, does not matter what pile, as long as it's last card, that last card will change.

**Comment by tvledesign** [comment]
This should be fixed in the latest.

**Comment by tvledesign** [comment]
This should be fixed in the latest.

**Comment by JoeBSong** [comment]
Confirmed that this is fixed.
