### ISSUE TITLE
New deck generate 2019.1.1f1

### ISSUE THREAD

**Issue by JoeBSong** [tvledesign/standard-deck-manager#23]
Having cards in the in use or discard, hitting generating new deck save, switch, and back causes this  bug to happen where the cards change to 1 single card with no value.

before
![image](https://user-images.githubusercontent.com/31709530/58721819-75bcfc80-839b-11e9-8617-297075577a7a.png)

after
![image](https://user-images.githubusercontent.com/31709530/58721840-82415500-839b-11e9-82f6-ce70860c1996.png)

**Comment by JoeBSong** [comment]
This also occurs in 2018 version as well except it Card editor is filled in with the correct card.

**Comment by JoeBSong** [comment]
This does not happen in the 2017 version.

**Comment by tvledesign** [comment]
@JoeBSong can you check if this bug still happens with all the latest fixes.

**Comment by JoeBSong** [comment]
confirmed fixed
