### ISSUE TITLE
E button

### ISSUE THREAD

**Issue by JoeBSong** [tvledesign/standard-deck-manager#25]
When pressing the E under DECK pile, save, change, and switching back, the last cards all turn into red king of hearts

![image](https://user-images.githubusercontent.com/31709530/73491606-9d25f800-4374-11ea-83f4-1790fceff364.png)

**Comment by JoeBSong** [comment]
Looks like this happens on a created prefab (The one I made)

**Comment by tvledesign** [comment]
@JoeBSong should be fixed since the last couple bug fixes. Please confirm.

**Comment by JoeBSong** [comment]
Confirmed fixed
