### ISSUE TITLE
Card Editor - Discard

### ISSUE THREAD

**Issue by JoeBSong** [tvledesign/standard-deck-manager#26]
When changing the card in the Discard Pile save, switch, upon looking at the card it saves as the correct saved card but upon clicking it, it reverts back to the original card it was.

Before:
![image](https://user-images.githubusercontent.com/31709530/73494765-c8134a80-437a-11ea-9fed-9b7d383f4d52.png)

Before clicking
![image](https://user-images.githubusercontent.com/31709530/73494795-d7929380-437a-11ea-9bdf-cc4b214fab47.png)

After:
![image](https://user-images.githubusercontent.com/31709530/73494812-e0836500-437a-11ea-957b-1d519c0f8720.png)

**Comment by JoeBSong** [comment]
Looks to be happening on the DeckManager Prefab in the Prefabs folder.

**Comment by tvledesign** [comment]
@JoeBSong should be fixed now please confirm.

**Comment by JoeBSong** [comment]
Confirmed fixed.
