### ISSUE TITLE
Created Prefab

### ISSUE THREAD

**Issue by JoeBSong** [tvledesign/standard-deck-manager#28]
When hitting play button with my created prefab of the DeckManager is causes the bottom half to turn into one card of the same suite and number.

before
![image](https://user-images.githubusercontent.com/31709530/73790950-050a8300-4767-11ea-8093-2e8c42e4ff02.png)

After
![image](https://user-images.githubusercontent.com/31709530/73790962-0cca2780-4767-11ea-8d63-37cab427dd61.png)

**Comment by tvledesign** [comment]
@JoeBSong this should be fixed when the generating deck bug was fixed. Please confirm.

**Comment by JoeBSong** [comment]
Confirmed fix
