### ISSUE TITLE
Generating new Deck - Play Mode

### ISSUE THREAD

**Issue by JoeBSong** [tvledesign/standard-deck-manager#29]
In play mode when generating a new deck the last two cards turn into black ace of clubs.

Before
![image](https://user-images.githubusercontent.com/31709530/73792520-16a15a00-476a-11ea-88c7-6cfdd8bbf964.png)

After
![image](https://user-images.githubusercontent.com/31709530/73792537-1dc86800-476a-11ea-99bb-18fb165e6123.png)

**Comment by tvledesign** [comment]
@JoeBSong this should have been fixed when the other generate deck bug was fixed. Please confirm.

**Comment by JoeBSong** [comment]
This still happens

Original prefab after generating a new deck
![image](https://user-images.githubusercontent.com/31709530/74484776-e13df000-4e7e-11ea-8388-1cd89fedfc09.png)

myDeck prefab after generating a new deck
![image](https://user-images.githubusercontent.com/31709530/74484725-c4a1b800-4e7e-11ea-8ee7-092fef41d7ca.png)

**Comment by JoeBSong** [comment]
This seems to happen when switch prefab from myDeck and orignal prefab. Confirmed fixed
