### ISSUE TITLE
Generating new deck - Original Prefab

### ISSUE THREAD

**Issue by JoeBSong** [tvledesign/standard-deck-manager#30]
Using the Original Prefab, when generating a new deck, save, switch, and back it keeps the card name as is but upon checking under Card editor it has the wrong Card in it.

Before
![image](https://user-images.githubusercontent.com/31709530/74485897-6a562680-4e81-11ea-8a64-a06ba19e4a21.png)

After
![image](https://user-images.githubusercontent.com/31709530/74486089-c9b43680-4e81-11ea-913a-9ed502c1dbbe.png)

**Comment by tvledesign** [comment]
@JoeBSong please confirm if fixed with new push.

**Comment by JoeBSong** [comment]
Confirmed fixed
