### ISSUE TITLE
Shuffle to Top Deck - Deck to Discard

### ISSUE THREAD

**Issue by JoeBSong** [tvledesign/standard-deck-manager#38]
Under To Top of Discard Pile: Pressing Deck removes all the cards in deck but the under Discard it says 52 cards are in it but visually it shows just the 13 cards. Upon Saving and switching scene and back all the cards are back visually.

Before
![image](https://user-images.githubusercontent.com/31709530/78754012-62c07480-793c-11ea-8d43-f92391f82146.png)

button pressed
![image](https://user-images.githubusercontent.com/31709530/78754908-e890ef80-793d-11ea-87c6-7890ee2927be.png)

Save, Switched
![image](https://user-images.githubusercontent.com/31709530/78754151-9e5b3e80-793c-11ea-8a5a-95763d71f5a4.png)

**Comment by JoeBSong** [comment]
happens with Top of In Use pile as well

**Comment by tvledesign** [comment]
Just push through an update @JoeBSong please confirm if fixed.

**Comment by JoeBSong** [comment]
Confirmed fixed
